title: Automation
id: automation
path: automation
icon: "mdi:robot"
cards:
  - cards:
      - entities:
          - entity: input_boolean.lights_automation_living_room_off_after_sunrise
          - entity: input_boolean.lights_automation_bedroom_on_before_work
          - entity: input_boolean.lights_automation_bedroom_lamps_with_alarm
          - entity: input_boolean.lights_automation_bedroom_lamps_off_after_alarm
          - entity: input_datetime.alarm_time
          - entity: input_datetime.lamp_off_time
        title: Morning
        type: entities
      - entities:
          - entity: input_boolean.lights_automation_living_room_on_in_evening
          - entity: input_boolean.lights_automation_living_room_on_in_evening_during_vacation
          - entity: input_boolean.lights_automation_living_room_off_at_night_during_vacation
        show_header_toggle: false
        title: Evening
        type: entities
    type: vertical-stack
  - cards:
      - entities:
          - entity: input_boolean.beto_automation_disable
          - entity: input_boolean.beto_automation_run_on_weekdays
        show_header_toggle: false
        title: Vacuum
        type: entities
      - entities:
          - entity: input_boolean.switches_automation_christmas_tree
        show_header_toggle: false
        title: Seasonal
        type: entities
      - entities:
          - entity: input_boolean.mode_vacation
          - entity: input_boolean.mode_guest
        show_header_toggle: false
        title: Modes
        type: entities
      - entities:
          - entity: script.lights_night_lighting
          - entity: script.beto_run_on_command
        show_header_toggle: false
        title: Scripts
        type: entities
    type: vertical-stack
