title: Automation
id: automation
path: automation
icon: 'mdi:robot'
cards:
  - cards:
      - entities:
          - entity: input_boolean.vacation_mode
          - entity: input_boolean.guest_mode
        show_header_toggle: false
        title: Modes
        type: entities
      - entities:
          - entity: input_boolean.disable_beto
          - entity: input_boolean.automation_beto_on_weekdays
          - entity: input_boolean.automation_lights_off_after_sunrise
          - entity: input_boolean.automation_lights_living_room_on_evening
          - entity: input_boolean.automation_lights_bedroom_on_before_work
          - entity: input_boolean.automation_lights_on_in_evening_during_vacation
          - entity: input_boolean.automation_lights_off_at_night_during_vacation
        show_header_toggle: false
        title: Automation Overrides
        type: entities
    type: vertical-stack