homeassistant: !include homeassistant.yaml
default_config:

alexa_media: !include alexa_media.yaml
automation: !include_dir_list automation
group: !include_dir_named group
hacs: !include hacs.yaml
hue: !include hue.yaml
input_boolean: !include_dir_named input_boolean
light: !include_dir_merge_list light
lovelace: !include lovelace.yaml
media_player: !include_dir_merge_list media_player
neato: !include neato.yaml
person: !include persons.yaml
pi_hole: !include pihole.yaml
scene: !include scenes.yaml
script: !include_dir_named script
sensor: !include sensor.yaml
spotify: !include spotify.yaml
switch: !include switch.yaml
tts: !include tts.yaml
vacuum: !include vacuum.yaml
zone: !include zones.yaml