homeassistant: !include homeassistant.yaml
default_config:

automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
cloud: !include cloud.yaml
group: !include group.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
light: !include_dir_merge_list light
notify: !include notify.yaml
proximity: !include proximity.yaml
script: !include_dir_merge_named script
scene: !include scene.yaml
tts: !include tts.yaml
