homeassistant: !include homeassistant.yaml
default_config:

tts:
  - platform: google_translate

ifttt:
  key: !secret ifttt_api_key

#################################################
## Includes
#################################################
automation: !include_dir_list automation
input_boolean: !include_dir_named input_boolean
group: !include_dir_named group
hue: !include hue.yaml
light: !include_dir_merge_list light
lovelace: !include lovelace.yaml
media_player: !include_dir_merge_list media_player
person: !include persons.yaml
scene: !include scenes.yaml
script: !include_dir_named script
sensor: !include sensor.yaml
spotify: !include spotify.yaml
switch: !include switch.yaml
zone: !include zones.yaml