homeassistant: !include homeassistant.yaml
default_config:

automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensor.yaml
cloud: !include cloud.yaml
group: !include_dir_named group
hue: !include hue.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
light: !include_dir_merge_list light
lovelace: !include lovelace.yaml
lutron_caseta: !include lutron.yaml
# neato: !include neato.yaml
nest: !include nest.yaml
person: !include persons.yaml
proximity: !include proximity.yaml
samsungtv: !include samsung-tv.yaml
scene: !include scenes.yaml
script: !include_dir_merge_list script
sensor: !include sensor.yaml
spotify: !include spotify.yaml
switch: !include switch.yaml
tplink: !include tplink.yaml
tts: !include tts.yaml
zone: !include zones.yaml