
homeassistant: !include homeassistant.yaml
  

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

lovelace: !include lovelace.yaml

tts:
  - platform: google_translate

ifttt:
  key: !secret ifttt_api_key

#################################################
## Components
#################################################
hue:
  bridges:
    - host: !secret philips_hue_ip
      allow_hue_groups: false
      allow_unreachable: true

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

media_player:
  - platform: androidtv
    name: Fire TV Stick
    host: !secret amazon_fire_tv_ip

#################################################
## Includes
#################################################
automation: !include_dir_merge_list automation
input_boolean: !include input_boolean.yaml
group: !include_dir_named groups
light: !include light_group.yaml
person: !include persons.yaml
scene: !include scenes.yaml
script: !include_dir_named scripts
sensor: !include sensor.yaml
switch: !include switch.yaml
zone: !include zones.yaml