#################################################
## Living Room
#################################################
- platform: group
  name: Living Room Lamps
  entities: 
    - light.living_room_1
    - light.living_room_2

#################################################
## Bedroom
#################################################
- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_1
    - light.bedroom_2