- platform: group
  name: family
  services:
    - service: mobile_app_pixel_7
    - service: mobile_app_allisons_phone
- platform: group
  name: owen
  services:
    - service: mobile_app_pixel_7
- platform: group
  name: allison
  services:
    - service: mobile_app_allisons_phone
