title: Admin
views:
  - !include lovelace/view-home.yaml
  - !include lovelace/view-lights.yaml
  - !include lovelace/view-people.yaml
  - !include lovelace/view-media.yaml
  - !include lovelace/view-vacuum.yaml
  - !include lovelace/view-weather.yaml
  - !include lovelace/view-server.yaml
  - !include lovelace/view-automations.yaml