#################################################
## Run Beto on Weekdays
#################################################

alias: Run Beto on Weekdays
initial_state: 'on'
trigger:
  - platform: time
    at: '10:00'

condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: vacuum.beto
    state: 'docked'
  - condition: numeric_state
    entity_id: sensor.beto_battery_level
    above: 99
  - condition: state
    entity_id: input_boolean.beto_automation_disable
    state: 'off'
  - condition: state
    entity_id: input_boolean.mode_vacation
    state: 'off'
  - condition: state
    entity_id: input_boolean.beto_automation_run_on_weekdays
    state: 'on'

action:
  - service: vacuum.start
    entity_id:
      - vacuum.beto