#################################################
## Bedroom
#################################################
- platform: group
  name: Bedroom
  entities:
    - light.bedroom_1
    - light.bedroom_2
    - light.master_bedroom_bedroom_lights