#################################################
## Bedroom Lamps
#################################################
- platform: group
  name: Bedroom Lamps
  entities:
    - light.allison_bedroom_lamp
    - light.owen_bedroom_lamp
