#################################################
## Bedroom
#################################################
- platform: group
  name: Bedroom
  entities:
    - light.bedroom_1
    - light.bedroom_2