#################################################
## Bedroom Lamps
#################################################
- platform: group
  name: Bedroom Lamps
  entities:
    - light.bedroom_1
    - light.bedroom_2