#################################################
## Turn off Christmas tree during the day
#################################################

alias: Turn off Christmas tree during the day
initial_state: 'on'
trigger:
  - platform: time
    at: '09:00:00'

condition:
  - condition: state
    entity_id: input_boolean.switches_automation_christmas_tree
    state: 'on'

action:
  - service: switch.turn_off
    entity_id:
      - switch.christmas_tree
