#################################################
## Turn on Christmas tree in the morning
#################################################

alias: Turn on Christmas tree in the morning
initial_state: 'on'
trigger:
  - platform: time
    at: '06:00:00'

condition:
  - condition: state
    entity_id: input_boolean.switches_automation_christmas_tree
    state: 'on'
  - condition: state
    entity_id: input_boolean.mode_vacation
    state: 'off'

action:
  - service: switch.turn_on
    entity_id:
      - switch.christmas_tree
