esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${ip_address}

logger:

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_password

switch:
- platform: gpio
    name: "Open Garage Door"
    pin: 5

binary_sensor:
  - platform: gpio
    name: "Garaga Door is closed"
    pin:
      number: 16
      mode: INPUT_PULLUP