esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP32
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${ip_address}

logger:

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_password

switch:
- platform: gpio
    name: ${friendly_name} Press Button
    pin: 4

binary_sensor:
  - platform: gpio
    name: ${friendly_name} State
    pin:
      number: 16
      mode: INPUT_PULLUP