# Garage Open While Away
- alias: Garage - Open While Away
  id: garage_open_while_away

  trigger:
    - platform: numeric_state
      entity_id: proximity.family
      above: 5

  condition:
    - condition: state
      entity_id: proximity.family
      attribute: dir_of_travel
      state: away_from
    - condition: state
      entity_id: cover.primary_garage_door
      state: "open"

  action:
    - alias: "Set up variables for actions"
      variables:
        action_close: "{{ 'ACTION_CLOSE' ~ context.id }}"
    - alias: "Notify garage open"
      service: notify.owen
      data:
        message: Garage door is open.
        data:
          actions:
            - action: "{{ action_close }}"
              title: "Close Garage"
    - alias: "Wait for a response"
      wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "{{ action_close }}"
    - alias: "Perform action"
      choose:
        - conditions: "{{ wait.trigger.event.data.action == action_close }}"
          sequence:
            - service: cover.close_cover
              target: 
                entity_id: cover.primary_garage_door
