#################################################
## Turn off bedroom lamps after alarm
#################################################

alias: Turn off bedroom lamps after alarm
initial_state: "on"
trigger:
  - platform: time
    at: input_datetime.lamp_off_time

condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    # To make sure we aren't using the default time
    after: "01:00:00"
  - condition: state
    entity_id: person.owen
    state: "home"
  - condition: state
    entity_id: input_boolean.mode_vacation
    state: "off"
  - condition: state
    entity_id: input_boolean.mode_guest
    state: "off"
  - condition: state
    entity_id: input_boolean.lights_automation_bedroom_lamps_off_after_alarm
    state: "on"

action:
  - service: light.turn_off
    data:
      entity_id: light.bedroom_lamps
