#################################################
## Turn on bedroom lamps with alarm
#################################################

alias: Turn on bedroom lamps with alarm
initial_state: "on"
trigger:
  - platform: time
    at: "06:00:00"

condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: person.owen
    state: "home"
  - condition: state
    entity_id: input_boolean.mode_vacation
    state: "off"
  - condition: state
    entity_id: input_boolean.mode_guest
    state: "off"
  - condition: state
    entity_id: input_boolean.lights_automation_bedroom_lamps_with_alarm
    state: "on"

action:
  - service: light.turn_on
    data:
      entity_id: light.bedroom_lamps
      brightness: 40
