#################################################
## Turn off living room lights at night during vacation
#################################################

alias: Turn off lights at night during vacation
initial_state: 'on'
trigger:
  - platform: time
    at: '21:30:00'
    
condition:
- condition: state
  entity_id: input_boolean.vacation_mode
  state: 'on'
- condition: state
  entity_id: input_boolean.lights_automation_living_room_off_at_night_during_vacation
  state: 'on'

action:
  - service: light.turn_off
    data:
      entity_id: light.living_room_lamps