#################################################
## Turn on bedroom lights before work
#################################################

alias: Turn on bedroom lights before work
initial_state: 'on'
trigger:
  - platform: time
    at: '08:45:00'
    
condition:
- condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
- condition: state
  entity_id: person.owen
  state: 'home'
- condition: state
  entity_id: input_boolean.mode_vacation
  state: 'off'
- condition: state
  entity_id: input_boolean.mode_guest
  state: 'off'
- condition: state
  entity_id: input_boolean.lights_automation_bedroom_on_before_work
  state: 'on'

action:
  - service: light.turn_on
    data:
      entity_id: light.bedroom_lights
      brightness: 255