#################################################
## Turn on living room lights in evening
#################################################

alias: Turn on living room lights in evening
initial_state: 'on'
trigger:
  - platform: sun
    event: 'sunset'
    offset: '-01:00:00'

condition:
- condition: state
  entity_id: person.owen
  state: 'home'
- condition: state
  entity_id: input_boolean.mode_vacation
  state: 'off'
- condition: state
  entity_id: input_boolean.lights_automation_living_room_on_in_evening
  state: 'on'

action:
  - service: light.turn_on
    entity_id:
      - light.living_room_lamps