##########################################################
## Christmas Tree
##########################################################

# Turn on Christmas tree in the morning
- alias: Turn on Christmas tree in the morning
  id: 'christmas_tree_on_in_morning'

  initial_state: 'on'
  trigger:
    - platform: time
      at: '06:00:00'

  condition:
    - condition: state
      entity_id: input_boolean.christmas_tree_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

# Turn on Christmas tree in the evening
- alias: Turn on Christmas tree in the evening
  id: 'christmas_tree_on_in_evening'

  initial_state: 'on'
  trigger:
    - platform: time
      at: '15:00:00'

  condition:
    - condition: state
      entity_id: input_boolean.christmas_tree_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

# Turn off Christmas tree during the day
- alias: Turn off Christmas tree during the day
  id: 'christmas_tree_off_during_day'

  initial_state: 'on'
  trigger:
    - platform: time
      at: '08:30:00'

  condition:
    - condition: state
      entity_id: input_boolean.christmas_tree_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

# Turn off Christmas tree at night
- alias: Turn off Christmas tree at night
  id: 'christmas_tree_off_at_night'

  initial_state: 'on'
  trigger:
    - platform: time
      at: '23:00:00'

  condition:
    - condition: state
      entity_id: input_boolean.switches_automation_christmas_tree
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree
