##########################################################
## Climate
##########################################################

# Set Temperature to Day Temp
- alias: Climate - Set Temperature to Day Temperature
  id: "climate_set_to_day_temp"

  initial_state: true
  trigger:
    - platform: time
      at: input_datetime.climate_day_start

  condition:
    - condition: state
      entity_id: input_boolean.climate_automations
      state: "on"
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: "off"

  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.kitchen_thermostat
      data:
        temperature: "{{ states('input_number.climate_day_temp') | int }}"

# Set Temperature to Night Temp
- alias: Climate - Set Temperature to Night Temperature
  id: "climate_set_to_night_temp"

  initial_state: true
  trigger:
    - platform: time
      at: input_datetime.climate_night_start

  condition:
    - condition: state
      entity_id: input_boolean.climate_automations
      state: "on"
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: "off"

  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.kitchen_thermostat
      data:
        temperature: "{{ states('input_number.climate_night_temp') | int }}"

# Away From Home Notification
- alias: Climate - Away from Home Notification
  id: climate_away_from_home_notification

  trigger:
    - platform: numeric_state
      entity_id: proximity.owen
      above: 30

  condition:
    - condition: state
      entity_id: proximity.owen
      attribute: dir_of_travel
      state: away_from
    - condition: state
      entity_id: input_boolean.climate_automations
      state: "on"

  action:
    - service: notify.owen
      data:
        message: You appear to be away from home.
        data:
          tag: climate
          group: climate
          entity_id: climate.hallway
          actions:
            - action: "climate_away"
              title: "Set Away Temperature"
              uri: "/lovelace/climate"

# Coming Back Home
- alias: Climate - Coming Back Home
  id: climate_coming_back_home

  trigger:
    - platform: numeric_state
      entity_id: proximity.owen
      below: 30

  condition:
    - condition: state
      entity_id: proximity.owen
      attribute: dir_of_travel
      state: towards
    - condition: state
      entity_id: input_boolean.climate_automations
      state: "off"

  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.kitchen_thermostat
      data:
        temperature: "{{ states('input_number.climate_day_temp') | int }}"
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.climate_automations
    - service: notify.owen
      data:
        message: Climate automation turned back on.
        data:
          tag: climate
          group: climate
          entity_id: climate.kitchen_thermostat
          actions:
            - action: "climate_away"
              title: "Please don't."
              uri: "/lovelace-admin/climate"
