# Turn on bedroom fan if late and warm
- alias: Climate - Bedroom Fan When Warm
  id: climate_bedroom_fan_when_warm

  trigger:
    - platform: time
      at: "21:00:00"

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.owen
          state: "home"
        - condition: state
          entity_id: person.allison
          state: "home"
    - condition: template
      value_template: "{{ states('sensor.bedroom_temperature_sensor_temperature') | float > states_attr('climate.main', 'temperature') | int }}"

  action:
    - service: switch.turn_on
      entity_id: switch.bedroom_fan
