##########################################################
## Climate
##########################################################

# Set Temperature to Day Temp
- alias: Set Temperature to Day Temperature
  id: 'climate_set_to_day_temp'

  initial_state: 'on'
  trigger:
    - platform: time
      at: input_datetime.climate_day_start

  condition:
    - condition: state
      entity_id: input_boolean.climate_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'

  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.hallway
      data:
        temperature: "{{ states('input_number.climate_day_temp') | int }}"

# Set Temperature to Night Temp
- alias: Set Temperature to Night Temperature
  id: 'climate_set_to_night_temp'

  initial_state: 'on'
  trigger:
    - platform: time
      at: input_datetime.climate_night_start

  condition:
    - condition: state
      entity_id: input_boolean.climate_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'

  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.hallway
      data:
        temperature: "{{ states('input_number.climate_night_temp') | int }}"