# Garage Open While Away
- alias: Garage - Open While Away
  id: garage_open_while_away

  trigger:
    - platform: numeric_state
      entity_id: proximity.family
      above: 5

  condition:
    - condition: state
      entity_id: proximity.family
      attribute: dir_of_travel
      state: away_from
    - condition: state
      entity_id: cover.primary_garage_door
      state: "open"

  action:
    - service: notify.family
      data:
        message: Garage door is open.
        entity_id: cover.primary_garage_door
        actions:
          - action: "garage_close"
            title: "Close Garage"
            uri: "/lovelace/home"
