##########################################################
## Holiday
##########################################################

# Turn on Christmas tree
- alias: Holiday - Turn on Christmas tree
  id: "holiday_christmas_tree_on"

  initial_state: true
  trigger:
    - platform: time
      at: "07:00:00"
    - platform: state
      entity_id: person.allison
      to: "home"

  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: "on"
    - condition: state
      entity_id: switch.christmas_tree_smart_plug
      state: "off"
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: "off"

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree_smart_plug

# Turn off Christmas tree
- alias: Holiday - Turn off Christmas tree
  id: "holiday_christmas_tree_off"

  initial_state: true
  trigger:
    - platform: state
      entity_id: person.allison
      to: "not_home"
      for: "00:05:00"
    - platform: time
      at: "23:00:00"

  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: "on"
    - condition: state
      entity_id: switch.christmas_tree_smart_plug
      state: "on"
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: "off"

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree_smart_plug
