##########################################################
## Holiday
##########################################################

# Turn on Christmas tree when Allison gets home
- alias: Holiday - Turn on Christmas tree when Allison gets home
  id: 'holiday_christmas_tree_on_when_allison_gets_home'

  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: person.allison
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.christmas_tree_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree
        - switch.strip_light

# Turn off Christmas tree when Allison leaves
- alias: Holiday - Turn off Christmas tree when Allison leaves
  id: 'holiday_christmas_tree_off_when_allison_leaves'

  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: person.allison
      to: 'not_home'
      for: '00:05:00'

  condition:
    - condition: state
      entity_id: input_boolean.christmas_tree_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: person.allison
      state: 'not_home'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree
        - switch.strip_light

# Turn on holiday lights
- alias: Holiday - Turn on holiday lights
  id: 'holiday_lights_on'

  initial_state: 'on'
  trigger:
    - platform: time
      at: '05:00:00'
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 4

  action:
    - service: switch.turn_on
      entity_id:
        - switch.outside_front_left_plug
        - switch.outside_back_left_plug
        - switch.christmas_tree
        - switch.strip_light

# Turn off holiday lights
- alias: Holiday - Turn off holiday lights
  id: 'holiday_lights_off'

  initial_state: 'on'
  trigger:
    - platform: time
      at: '08:30:00'
    - platform: time
      at: '23:00:00'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.outside_front_left_plug
        - switch.outside_back_left_plug
        - switch.christmas_tree
        - switch.strip_light