##########################################################
## Holiday
##########################################################

# Turn on Christmas tree
- alias: Holiday - Turn on Christmas tree
  id: "holiday_christmas_tree_on"

  initial_state: true
  trigger:
    - platform: time
      at: "07:00:00"
    - platform: state
      entity_id: person.allison
      to: "home"

  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: "on"
    - condition: state
      entity_id: switch.christmas_tree
      state: "off"
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: "off"

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree
        - switch.strip_light

# Turn off Christmas tree
- alias: Holiday - Turn off Christmas tree
  id: "holiday_christmas_tree_off"

  initial_state: true
  trigger:
    - platform: state
      entity_id: person.allison
      to: "not_home"
      for: "00:05:00"
    - platform: time
      at: "23:00:00"

  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: "on"
    - condition: state
      entity_id: switch.christmas_tree
      state: "on"
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: "off"

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree
        - switch.strip_light

# Turn on holiday lights
- alias: Holiday - Turn on holiday lights
  id: "holiday_lights_on"

  initial_state: true
  trigger:
    - platform: time
      at: "05:00:00"
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 4

  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: "on"

  action:
    - service: switch.turn_on
      entity_id:
        - switch.outside_front_left_plug
        - switch.outside_front_right_plug

# Turn off holiday lights
- alias: Holiday - Turn off holiday lights
  id: "holiday_lights_off"

  initial_state: true
  trigger:
    - platform: time
      at: "08:30:00"
    - platform: time
      at: "23:00:00"

  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: "on"

  action:
    - service: switch.turn_off
      entity_id:
        - switch.outside_front_left_plug
        - switch.outside_front_right_plug
