##########################################################
## Bedroom
##########################################################

# Turn on bedroom lamps with alarm
- alias: Lights - Turn on bedroom lamps with alarm
  id: 'lights_bedroom_lamps_on_with_alarm'

  initial_state: 'on'
  trigger:
    - platform: time
      at: input_datetime.morning_alarm

  condition:
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: state
      entity_id: person.owen
      state: 'home'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'
    - condition: state
      entity_id: input_boolean.lights_bedroom_lamps_on_with_alarm
      state: 'on'

  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lamps
        brightness: 40


# Turn off bedroom lamps after alarm
- alias: Lights - Turn off bedroom lamps after alarm
  id: 'lights_bedroom_lamps_off_after_alarm'

  initial_state: 'on'
  trigger:
    - platform: time
      at: input_datetime.bedroom_lamp_off

  condition:
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: state
      entity_id: person.owen
      state: 'home'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'
    - condition: state
      entity_id: input_boolean.lights_bedroom_lamps_off_after_alarm
      state: 'on'

  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom_lamps

# Turn on bedroom lights before work
- alias: Lights - Turn on bedroom lights before work
  id: 'lights_overhead_bedroom_on_before_work'

  initial_state: 'on'
  trigger:
    - platform: time
      at: '08:30:00'

  condition:
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: state
      entity_id: person.owen
      state: 'home'
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: 'off'
    - condition: state
      entity_id: input_boolean.lights_bedroom_lights_on_before_work
      state: 'on'

  action:
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom_bedroom_lights
        brightness: 255

#########################################################
# Living Room
#########################################################

# Turn on living room lights when watching TV
- alias: Lights - Turn on living room lights when watching TV
  id: 'lights_living_room_lights_on_when_watching_tv'

  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.samsung_tv
      to: 'on'

  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_lamps
        brightness: 255

# Turn off living room lights when not watching TV
- alias: Lights - Turn off living room lights when not watching TV
  id: 'lights_living_room_lights_off_when_not_watching_tv'

  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.samsung_tv
      to: 'off'
      for: '00:05:00'

  condition:
    - condition: state
      entity_id: light.living_room_lamps
      state: 'on'
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 4
        - condition: state
          entity_id: person.owen
          state: 'away'
        - condition: state
          entity_id: binary_sensor.workday
          state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.living_room_lamps