##########################################################
## Bedroom
##########################################################

# Turn on bedroom lamps with alarm
- alias: Lights - Turn on bedroom lamps with alarm
  id: "lights_bedroom_lamps_on_with_alarm"

  initial_state: true
  trigger:
    - platform: time
      at: input_datetime.morning_alarm

  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
    - condition: state
      entity_id: person.owen
      state: "home"
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: "off"
    - condition: state
      entity_id: input_boolean.lights_bedroom_lamps_on_with_alarm
      state: "on"

  action:
    - service: scene.turn_on
      entity_id: scene.dim_bedroom

# Turn off bedroom lamps after alarm
- alias: Lights - Turn off bedroom lamps after alarm
  id: "lights_bedroom_lamps_off_after_alarm"

  initial_state: true
  trigger:
    - platform: time
      at: input_datetime.bedroom_lamp_off

  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
    - condition: state
      entity_id: person.owen
      state: "home"
    - condition: state
      entity_id: input_boolean.mode_vacation
      state: "off"
    - condition: state
      entity_id: input_boolean.lights_bedroom_lamps_off_after_alarm
      state: "on"

  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.bedroom_lamps

#########################################################
# Living Room
#########################################################

# Philips Hue Living Room Lights On
- alias: Lights - Turn on living room lights when philips hue switch on
  id: "lights_living_room_lights_on_when_philips_hue_switch_on"

  initial_state: true
  trigger:
    - platform: event
      event_type: "zha_event"
      event_data:
        device_id: !secret hue_remote_id
        args:
          button: "on"

  action:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.allison_living_room_lamp
          - switch.owen_living_room_lamp

# Philips Hue Living Room Lights Off
- alias: Lights - Turn off living room lights when philips hue switch off
  id: "lights_living_room_lights_off_when_philips_hue_switch_off"

  initial_state: true
  trigger:
    - platform: event
      event_type: "zha_event"
      event_data:
        device_id: !secret hue_remote_id
        args:
          button: "off"

  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.allison_living_room_lamp
          - switch.owen_living_room_lamp

# Philips Hue Turn on Living Room Automation
- alias: Lights - Turn on living room automation when philips hue switch brighter
  id: "lights_living_room_lights_automation_on_when_philips_hue_switch_brighter"

  initial_state: true
  trigger:
    - platform: event
      event_type: "zha_event"
      event_data:
        device_id: !secret hue_remote_id
        args:
          button: "up"

  condition:
    - condition: state
      entity_id: input_boolean.lights_living_room_automations
      state: "off"

  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.lights_living_room_automations
    - service: notify.alexa_media
      data:
        data:
          type: announce
        target: media_player.living_room_echo
        message: "Living Room Automation Turned On"

# Philips Hue Turn off Living Room Automation
- alias: Lights - Turn off living room automation when philips hue switch dimmer
  id: "lights_living_room_lights_automation_off_when_philips_hue_switch_dimmer"

  initial_state: true
  trigger:
    - platform: event
      event_type: "zha_event"
      event_data:
        device_id: !secret hue_remote_id
        args:
          button: "down"

  condition:
    - condition: state
      entity_id: input_boolean.lights_living_room_automations
      state: "on"

  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.lights_living_room_automations
    - service: notify.alexa_media
      data:
        data:
          type: announce
        target: media_player.living_room_echo
        message: "Living Room Automation Turned Off"

#########################################################
# Garage
#########################################################

# Turn on garage lights when garage door opening or motion
- alias: Lights - Turn on garage lights when garage door opening or motion
  id: "lights_turn_on_garage_lights_when_garage_door_opening_or_motion"

  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - cover.primary_garage_door
      to: "opening"
    - platform: state
      entity_id:
        - cover.primary_garage_door
      to: "open"
    - platform: state
      entity_id:
        - binary_sensor.garage_lights_motion_detection
      to: "on"

  condition:
    - condition: state
      entity_id: switch.garage_lights
      state: "off"

  action:
    - service: switch.turn_on
      target:
        entity_id: switch.garage_lights

# Turn off garage lights when garage door closed or no motion
- alias: Lights - Turn off garage lights when garage door closed or no motion
  id: "lights_turn_off_garage_lights_when_garage_door_closed_or_no_motion"

  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - cover.primary_garage_door
      to: "closed"
      for: "00:05:00"
    - platform: state
      entity_id:
        - binary_sensor.garage_lights_motion_detection
      to: "off"
      for: "00:05:00"

  condition:
    - condition: state
      entity_id: switch.garage_lights
      state: "on"
    - condition: state
      entity_id: binary_sensor.garage_lights_motion_detection
      state: "off"
    - condition: not # We want lights to turn off if garage door is unavailable.
      conditions:
        - condition: state
          entity_id: cover.primary_garage_door
          state: "open"

  action:
    - service: switch.turn_off
      target:
        entity_id: switch.garage_lights
