#################################################
## Turn off lights at sunrise
#################################################

- alias: Turn off lights after sunrise
  
  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '+00:45:00'

  condition:
    - condition: state
      entity_id: input_boolean.automation_lights_off_after_sunrise
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - group.interior_lights

#################################################
## Turn on living room lights in evening
#################################################

- alias: Turn on living room lights in evening

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-01:00:00'

  condition:
  - condition: state
    entity_id: person.owen
    state: 'home'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.automation_lights_living_room_on_evening
    state: 'on'
  
  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_lamps