##########################################################
## Phone Actions
##########################################################

# Set Climate to Away Temp and Turn Off Automation
- alias: Android Action - Climate Away Temp
  id: android_action_climate_away

  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "climate_away"

  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.hallway
      data:
        temperature: "{{ states('input_number.climate_away_temp') | int }}"
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.climate_automations