substitutions:
    device_name: downstairs-tv-smart-plug
    device_description: Power monitoring plug for downstairs TV
    friendly_name: Downstairs TV Smart Plug
    ip_address: !secret downstairs_tv_smart_plug_ip
    restore_mode: ALWAYS_ON

<<: !include common/sonoff_s31_common.yaml