substitutions:
    device_name: "downstairs-tv"
    device_description: Power monitoring plug for downstairs TV
    friendly_name: Downstairs TV
    ip_address: !secret downstairs_tv_smart_plug
    wattage_calibration: 67.6 -> 11.0
    amperage_calibration: 0.12 -> 0.08
    voltage_calibration1: 0.0 -> 0.0
    voltage_calibration2: 322.4 -> 118.3
    switch_restore_mode: ALWAYS_ON
  
<<: !include smart_plugs_common.yaml