substitutions:
  name: garage-door-primary
  friendly_name: Garage Door Primary
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: qQqQn/ZI1M1GASWABGYqhIzynwCxFMYbO89wEHFOdpE=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
