substitutions:
    device_name: modem-smart-plug
    device_description: Power monitoring plug for modem
    friendly_name: Internet Modem Smart Plug
    ip_address: !secret modem_smart_plug_ip
    restore_mode: ALWAYS_ON
  
<<: !include common/sonoff_s31_common.yaml