substitutions:
    device_name: "modem-smart-plug"
    device_description: Power monitoring plug for modem
    friendly_name: Internet Modem Smart Plug
    ip_address: !secret modem_smart_plug_ip
    wattage_calibration: 67.6 -> 11.0
    amperage_calibration: 0.12 -> 0.08
    voltage_calibration1: 0.0 -> 0.0
    voltage_calibration2: 322.4 -> 118.3
    restore_mode: ALWAYS_ON
  
<<: !include smart_plugs_common.yaml