substitutions:
    device_name: owen-computer-smart-plug
    device_description: Power monitoring plug for Owen's computer
    friendly_name: Owen Computer Smart Plug
    ip_address: !secret owen_computer_smart_plug_ip
    wattage_calibration: 67.6 -> 11.0
    amperage_calibration: 0.12 -> 0.08
    voltage_calibration1: 0.0 -> 0.0
    voltage_calibration2: 322.4 -> 118.3
    restore_mode: ALWAYS_ON
  
<<: !include cloudfree_smart_plug_common.yaml